FROM debian:buster-slim as builder

RUN apt-get update -y \
	&& apt-get -yy -q install --no-install-recommends --no-install-suggests --fix-missing \
		bash-static

RUN cp /bin/bash-static /sh

FROM gcr.io/kaniko-project/executor:multi-arch

COPY --from=0 /sh /usr/bin

ENV PATH /usr/local/bin:/bin:/usr/bin:/kaniko